on:
  schedule:
    # * is a special character in YAML so you have to quote this string
    - cron:  '*/5 * * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: install python packages
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create local changes
        run: |
          curl -X GET https://www.meldkamerspel.com/einsaetze.json > inzetten.json
          curl -X GET https://www.meldkamerspel.com/alliance_event_types.json > events.json
          python Update.py
        env:
          DISCORD: ${{ secrets.DISCORD  }}

      - name: json-syntax-check
        uses: limitusus/json-syntax-check@v1
        with:
          pattern: "\\.json$"

      - name: Prettify code
        uses: creyD/prettier_action@master
        with:
          prettier_options: --write **/*.{js,md,json}
          commit_message: Update files
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Check if there are changes
        id: git-check
        run: |
          git fetch origin main
          git diff --exit-code HEAD origin/main || echo "changed=true" >> $GITHUB_OUTPUT

      - name: Trigger external workflow
        if: steps.git-check.outputs.changed == 'true'
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: MeldkamerspelGameTeam/mks-complete-tracking
          event-type: run
          client-payload: '{"source-repo": "${{ github.repository }}", "commit": "${{ github.sha }}"}'
